"""
generate_data.py
----------------
This file creates a fake (synthetic) supply chain dataset and saves it as a CSV.

Why fake data?
  Real supply chain data from companies like Applied Materials is confidential.
  So we simulate realistic-looking data ourselves. The patterns we build in
  (seasonality, spikes, trends) are the same patterns a real dataset would have.
  Recruiters and students understand this - what matters is that the code works
  on data with the right shape and structure.

What does the dataset look like?
  Each row = one part's demand on one day.
  Columns:
    - date          : the calendar date
    - part_id       : a unique ID for a spare part (e.g. "PART_003")
    - category      : what kind of part it is (e.g. "Valve", "Sensor")
    - supplier      : which supplier makes it (e.g. "SupplierA")
    - region        : where it's used (e.g. "North America")
    - demand        : how many units were requested that day
    - inventory     : how many units are currently in stock
    - lead_time_days: how many days it takes to reorder and receive this part
    - price_usd     : unit cost of the part

This is a multivariate time series - multiple parts, each with its own
demand history and static attributes (category, supplier, etc.).
TFT is specifically designed to handle exactly this kind of data.
"""

import numpy as np
import pandas as pd
import os

# Set a random seed so the data looks the same every time you run this.
# Without this, you'd get different numbers each run, which makes debugging harder.
np.random.seed(42)


# --------------------------------------------------------------------------
# CONFIG - change these if you want more/fewer parts or a longer date range
# --------------------------------------------------------------------------

NUM_PARTS = 50  # number of unique spare parts
START_DATE = "2021-01-01"
END_DATE = "2024-12-31"

CATEGORIES = ["Valve", "Sensor", "Pump", "Controller", "Filter"]
SUPPLIERS = ["SupplierA", "SupplierB", "SupplierC", "SupplierD"]
REGIONS = ["North America", "Europe", "Asia Pacific", "Latin America"]


def generate_demand_signal(n_days: int, base: float, part_idx: int) -> np.ndarray:
    """
    Creates a realistic demand curve for a single part over n_days.

    Real-world demand has three overlapping components:
      1. Trend     - demand slowly grows or shrinks over years
      2. Seasonality - demand spikes in certain months every year
                       (e.g. Q4 factory maintenance season)
      3. Noise     - random day-to-day variation

    We also throw in occasional "spike" events (unexpected bulk orders,
    equipment failures causing rush orders) because those are very real
    in semiconductor supply chains.

    Args:
        n_days   : total number of days in our date range
        base     : the average daily demand for this part
        part_idx : used to give each part slightly different seasonality

    Returns:
        numpy array of daily demand values (all non-negative integers)
    """

    days = np.arange(n_days)

    # 1. Slow upward trend - demand increases ~20% over the full period
    trend = base * (1 + 0.2 * days / n_days)

    # 2. Yearly seasonality - peaks around day 270 each year (~October, end of Q3)
    #    Each part has a slightly different phase so they don't all peak together
    phase_shift = part_idx * (2 * np.pi / NUM_PARTS)
    seasonality = base * 0.3 * np.sin(2 * np.pi * days / 365 + phase_shift)

    # 3. Random noise - normally distributed, scaled to ~15% of base demand
    noise = np.random.normal(0, base * 0.15, n_days)

    # Combine all three
    demand = trend + seasonality + noise

    # 4. Random spikes - about 5 times per year, demand suddenly jumps 2-4x
    #    This simulates unexpected equipment failures or bulk maintenance orders
    n_spikes = int(n_days / 73)  # roughly every 73 days = ~5 per year
    spike_days = np.random.choice(n_days, size=n_spikes, replace=False)
    demand[spike_days] *= np.random.uniform(2.0, 4.0, size=n_spikes)

    # Make sure demand is never negative and is always a whole number
    demand = np.maximum(demand, 0).astype(int)

    return demand


def generate_dataset() -> pd.DataFrame:
    """
    Builds the full dataset: 50 parts × ~1461 days = ~73,000 rows.

    Each part gets:
      - A random category, supplier, and region (static - never changes)
      - A base demand level (some parts are high-demand, some are niche)
      - A lead time (how long reordering takes - affects urgency of forecasts)
      - A price (used later to calculate financial impact of stockouts)
      - A full daily demand history generated by generate_demand_signal()
      - An inventory level (starts at 30x base demand, depletes with demand)

    Returns:
        A pandas DataFrame with one row per (part, day)
    """

    date_range = pd.date_range(start=START_DATE, end=END_DATE, freq="D")
    n_days = len(date_range)

    all_rows = []

    for i in range(NUM_PARTS):
        part_id = f"PART_{i + 1:03d}"  # zero-padded: PART_001, PART_002, ...
        category = np.random.choice(CATEGORIES)
        supplier = np.random.choice(SUPPLIERS)
        region = np.random.choice(REGIONS)

        # Base demand varies a lot between parts - some are used daily,
        # some are niche components ordered rarely
        base_demand = np.random.randint(5, 80)

        lead_time = np.random.randint(3, 30)  # days to reorder
        price_usd = round(np.random.uniform(50, 5000), 2)

        demand_series = generate_demand_signal(n_days, base_demand, i)

        # Realistic inventory simulation with periodic restocking.
        # When stock drops below a reorder point (2x lead_time demand),
        # a reorder arrives after lead_time days and replenishes stock.
        # This keeps inventory at realistic levels throughout the 4 years
        # rather than depleting to zero and staying there.
        reorder_point = int(base_demand * lead_time * 2)  # trigger reorder here
        reorder_qty = int(base_demand * 60)  # order 60 days of supply

        inventory = np.zeros(n_days, dtype=int)
        inventory[0] = base_demand * 45  # start with 45 days of stock
        pending_reorder_day = -1  # day a pending reorder will arrive

        for d in range(1, n_days):
            # Receive pending reorder if it arrives today
            if d == pending_reorder_day:
                inventory[d] = inventory[d - 1] - demand_series[d - 1] + reorder_qty
                pending_reorder_day = -1
            else:
                inventory[d] = max(0, inventory[d - 1] - demand_series[d - 1])

            # Trigger a reorder if below reorder point and none pending
            if inventory[d] < reorder_point and pending_reorder_day == -1:
                pending_reorder_day = d + lead_time

        # Build one row per day for this part
        for d in range(n_days):
            all_rows.append(
                {
                    "date": date_range[d],
                    "part_id": part_id,
                    "category": category,
                    "supplier": supplier,
                    "region": region,
                    "demand": demand_series[d],
                    "inventory": inventory[d],
                    "lead_time_days": lead_time,
                    "price_usd": price_usd,
                }
            )

    df = pd.DataFrame(all_rows)

    # Sort by date then part so it reads naturally
    df = df.sort_values(["date", "part_id"]).reset_index(drop=True)

    return df


def save_dataset(df: pd.DataFrame, path: str = "data/supply_chain_data.csv") -> None:
    """Saves the dataframe to a CSV file."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    df.to_csv(path, index=False)
    print(f"Dataset saved to {path}")
    print(f"Shape: {df.shape[0]:,} rows x {df.shape[1]} columns")
    print(f"Date range: {df['date'].min().date()} to {df['date'].max().date()}")
    print(f"Unique parts: {df['part_id'].nunique()}")
    print(f"\nSample (first 5 rows):")
    print(df.head())


if __name__ == "__main__":
    print("Generating synthetic supply chain dataset...")
    df = generate_dataset()
    save_dataset(df)
