"""
model.py
--------
This file defines the TFT (Temporal Fusion Transformer) model configuration.

We are NOT writing the TFT architecture from scratch here.
The pytorch-forecasting library already has a production-grade TFT implementation
that matches the original Google Research paper exactly. Writing it from scratch
would take thousands of lines and isn't the point of this project.

What we ARE doing here:
  - Preparing the dataset into the exact format TFT expects
  - Configuring the model with the right input/output settings
  - Defining helper functions that train.py will call

-----------------------------------------------------------------------
A quick explanation of TFT for beginners:
-----------------------------------------------------------------------

You already know what an LSTM does - it reads a sequence one step at a time
and tries to remember what's important using a hidden state (memory).

TFT is smarter in three specific ways:

1. It separates inputs into three types:
   - PAST inputs: things we know historically (past demand, past inventory)
   - FUTURE inputs: things we know in advance (day of week, month, holidays)
   - STATIC inputs: things that never change per part (category, supplier, region)

   A plain LSTM lumps all of this together. TFT processes each type
   differently, which makes it much more accurate.

2. It uses a "Variable Selection Network" - before doing any forecasting,
   TFT learns WHICH of your input features actually matter. If day-of-week
   turns out to be useless for a particular part, TFT learns to ignore it.
   This is like automatic feature selection built into the model.

3. It uses self-attention (like in ChatGPT/BERT) to look back across the
   entire history and decide which past time steps are most relevant for
   the current prediction. An LSTM can only "see" the recent past clearly.
   TFT can jump back and say "the demand spike 6 months ago is relevant now."

The output is NOT just one number. TFT gives you prediction intervals:
  - p10: there's only a 10% chance real demand falls below this
  - p50: the median prediction (best single guess)
  - p90: there's only a 10% chance real demand exceeds this

For supply chain planning, the p90 is what you use for safety stock.
The p10 tells you the floor. This is far more useful than a single number.
-----------------------------------------------------------------------
"""

import pandas as pd
import numpy as np
from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.data import GroupNormalizer
from pytorch_forecasting.metrics import QuantileLoss
from typing import Tuple


# How many past days the model looks at to make a prediction.
# 90 days = roughly one quarter of business data. Enough to capture
# monthly seasonality patterns without being too slow to train.
ENCODER_LENGTH = 90

# How many days into the future we want to predict.
# 30 days = one month ahead, which is useful for reorder planning.
DECODER_LENGTH = 30


def load_and_prepare(csv_path: str) -> pd.DataFrame:
    """
    Loads the CSV and adds the columns TFT specifically needs.

    TFT requires:
      1. A time index column that is a plain integer (0, 1, 2, 3 ...)
         not an actual date. It needs to count consecutive time steps.
      2. All categorical columns to be string type (not integer codes).
      3. A group identifier - what makes each time series unique.
         Here that's part_id - each part is its own time series.

    Args:
        csv_path: path to the CSV generated by generate_data.py

    Returns:
        DataFrame ready to be fed into TimeSeriesDataSet
    """

    df = pd.read_csv(csv_path, parse_dates=["date"])
    df = df.sort_values(["part_id", "date"]).reset_index(drop=True)

    # TFT's normalizer requires the target and all real-valued columns to be
    # float32. Our CSV stores demand and inventory as integers - casting them
    # here prevents a torch.finfo() TypeError in pytorch-forecasting 1.7 + PyTorch 2.5.
    df["demand"] = df["demand"].astype("float32")
    df["inventory"] = df["inventory"].astype("float32")
    df["lead_time_days"] = df["lead_time_days"].astype("float32")
    df["price_usd"] = df["price_usd"].astype("float32")

    # TFT needs a plain integer time index per group.
    # We do this by ranking days within each part's history.
    # Part_001 day 1 = 0, day 2 = 1, ... Part_002 day 1 = 0, etc.
    df["time_idx"] = df.groupby("part_id")["date"].rank(method="first").astype(int) - 1

    # Add calendar features as future known covariates.
    # These are things we ALWAYS know about the future - we know what month
    # January will be even before we get there. TFT uses these to learn
    # seasonal patterns more directly.
    df["month"] = df["date"].dt.month.astype(str)  # "1" through "12"
    df["day_of_week"] = df["date"].dt.dayofweek.astype(str)  # "0"=Monday ... "6"=Sunday
    df["quarter"] = df["date"].dt.quarter.astype(str)  # "1" through "4"

    # All categorical columns must be strings for TFT's embedding layers
    for col in ["category", "supplier", "region"]:
        df[col] = df[col].astype(str)

    return df


def build_dataset(df: pd.DataFrame) -> Tuple[TimeSeriesDataSet, TimeSeriesDataSet]:
    """
    Splits the data into training and validation sets and wraps them in
    pytorch-forecasting's TimeSeriesDataSet format.

    Why not just use train_test_split()?
    Because this is time series data. You CANNOT shuffle rows randomly
    and split - that would mean your model is trained on future data
    and tested on past data (data leakage). Instead, we split by time:
      - Training:   everything up to the last 30 days of each part's history
      - Validation: the final 30 days (same length as our prediction horizon)

    TimeSeriesDataSet does a lot of heavy lifting:
      - Normalizes the target (demand) per group using GroupNormalizer
        so PART_001 (base demand ~5) and PART_050 (base demand ~79)
        are on comparable scales
      - Creates the sliding windows automatically (encoder + decoder pairs)
      - Handles the different input types (static, past, future known)

    Args:
        df: prepared DataFrame from load_and_prepare()

    Returns:
        (training_dataset, validation_dataset) tuple
    """

    # The cutoff point: we hold out the last DECODER_LENGTH time steps
    # for validation. Everything before that is training data.
    max_time_idx = df["time_idx"].max()
    validation_cutoff = max_time_idx - DECODER_LENGTH

    training = TimeSeriesDataSet(
        data=df[df["time_idx"] <= validation_cutoff],
        # What identifies each individual time series
        group_ids=["part_id"],
        # The integer time counter column
        time_idx="time_idx",
        # What we're trying to predict
        target="demand",
        # How far back the model can look
        min_encoder_length=ENCODER_LENGTH // 2,  # allow shorter sequences at start
        max_encoder_length=ENCODER_LENGTH,
        # How far ahead we're predicting
        min_prediction_length=1,
        max_prediction_length=DECODER_LENGTH,
        # Static covariates: describe the part itself, never change over time.
        # TFT learns "parts in category Valve from SupplierC tend to behave like X"
        static_categoricals=["part_id", "category", "supplier", "region"],
        # Static numerical: the lead time and price don't change per part.
        # TFT can learn "expensive parts with long lead times need more safety stock"
        static_reals=["lead_time_days", "price_usd"],
        # Time-varying inputs we know only for the PAST (not the future).
        # We don't know future inventory levels until they happen.
        time_varying_known_categoricals=["month", "day_of_week", "quarter"],
        # Time-varying inputs we know for BOTH past and future.
        # We always know what month it will be next January.
        time_varying_unknown_reals=["demand", "inventory"],
        # Normalize demand per part so the model doesn't think PART_050
        # is just "more important" because it has higher raw demand numbers.
        target_normalizer=GroupNormalizer(
            groups=["part_id"],
            transformation="softplus",  # softplus keeps values positive after normalizing
        ),
        # Include the last DECODER_LENGTH steps of training as context
        # so the validation set has proper historical context to look back at
        predict_mode=False,
    )

    # The validation set uses identical config but covers the held-out period
    validation = TimeSeriesDataSet.from_dataset(
        training,
        df,
        predict=True,  # only return the prediction window rows
        stop_randomization=True,  # no random sampling - deterministic for evaluation
    )

    return training, validation


def build_model(training_dataset: TimeSeriesDataSet) -> TemporalFusionTransformer:
    """
    Instantiates the TFT model from the training dataset configuration.

    The dataset object already knows all the input/output dimensions
    (how many categories per feature, how many numerical inputs, etc.)
    so we pass it directly to from_dataset() which handles the architecture
    sizing automatically.

    Args:
        training_dataset: the TimeSeriesDataSet built by build_dataset()

    Returns:
        A configured TemporalFusionTransformer ready for training
    """

    model = TemporalFusionTransformer.from_dataset(
        training_dataset,
        # Learning rate - how big a step the optimizer takes each iteration.
        # 3e-3 is a good starting point for TFT; we'll use a scheduler in train.py
        # to reduce it automatically when validation loss stops improving.
        learning_rate=3e-3,
        # Hidden size controls the width of the model's internal layers.
        # 64 is a good balance: large enough to learn patterns, small enough
        # to train quickly on a laptop/single GPU.
        hidden_size=64,
        # Number of attention heads. Multi-head attention lets the model
        # look for multiple different patterns simultaneously.
        # Think of it like having 4 different "lenses" to view the past.
        attention_head_size=4,
        # Dropout randomly zeros out 10% of neurons during training.
        # This forces the model not to over-rely on any single feature,
        # which helps it generalize to new data (reduces overfitting).
        dropout=0.1,
        # Hidden continuous size: dimension of the embedding for numerical inputs.
        hidden_continuous_size=32,
        # We predict three quantiles instead of one single number.
        # p10 = lower bound, p50 = median, p90 = upper bound.
        # QuantileLoss trains the model to be well-calibrated across all three.
        loss=QuantileLoss(quantiles=[0.1, 0.5, 0.9]),
        # Print extra info about the model structure when it's created
        log_interval=10,
        log_val_interval=1,
        reduce_on_plateau_patience=3,  # reduce LR if val loss doesn't improve for 3 epochs
    )

    return model
